apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: akhan
  labels:
    app: app
spec:
  replicas: 1
  strategy:
    type: Recreate
  minReadySeconds: 20
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: db-secret
        name: app-deployment
        image: registry.dev.afsmtddso.com/akhan-harbor-project/app:ebaefd3-ddbae3b
        - containerPort: 5000
